// <auto-generated />
namespace RssFeedySharp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FeedUserAndItemUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedUserAndItemUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201305090032314_FeedUserAndItemUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
